add redux and connect frontend to backend
React-FACT/HienLPV pull request #2
Opened 2022-03-06 06:46 UTC by hienlpv

2022-03-06 07:33 UTC, mahoangnhatphi requested changes

2022-03-06 07:33 UTC, mahoangnhatphi commented on frontend/src/api/user.js
> +    const user = await axios.get(baseURI + 'auth/get-all');
Please add paths to contants

2022-03-06 07:33 UTC, mahoangnhatphi commented on frontend/src/components/Modal.jsx
> +    title: 'ADD NEW USER',
Move to constants

2022-03-06 07:33 UTC, mahoangnhatphi commented on frontend/src/pages/dashboard/index.jsx
> +              <td>{new Date().toLocaleDateString()}</td>
Use date format lib to ready for adapting with any format

2022-03-06 07:47 UTC, hienlpv commented on frontend/src/components/Modal.jsx
> +    title: 'ADD NEW USER',
this is contants

2022-03-06 22:05 UTC, mahoangnhatphi requested changes

2022-03-06 22:05 UTC, mahoangnhatphi commented on frontend/src/components/Modal.jsx
>      submit: 'Save',
Move these labels to constants for reuse

2022-03-07 09:13 UTC, mahoangnhatphi requested changes

2022-03-07 09:13 UTC, mahoangnhatphi commented on backend/src/logger/logs/errors.log
>  [2022-03-06 13:42:28] [[32minfo[39m]: ==================== AuthenticationRepository, call method GetAll ====================
Please add this file to `.gitignore`

2022-03-07 09:38 UTC, mahoangnhatphi approved these changes
ok

2022-03-07 09:38 UTC, merged